project_id = "tjichtlakmntmpxyxrzh"

[functions.chatwoot-webhook]
verify_jwt = false

[functions.chatwoot-send]
verify_jwt = false

[functions.ai-secretaria]
verify_jwt = false

[functions.ai-recuperacao]
verify_jwt = false

[functions.recovery-cron]
verify_jwt = false

[functions.lgpd-cron]
verify_jwt = false

[functions.report-cron]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.ai-report]
verify_jwt = false

[functions.ai-score]
verify_jwt = false