project_id = "tjichtlakmntmpxyxrzh"

[functions.chatwoot-webhook]
verify_jwt = false

[functions.chatwoot-send]
verify_jwt = false

[functions.ai-secretaria]
verify_jwt = false

[functions.ai-recuperacao]
verify_jwt = false